### ISSUE TITLE
Does not install on macOS M2(?)

### ISSUE THREAD

**Issue by danawoodman** [vlang/vls#385]
### V doctor
```
OS: macos, macOS, 12.5.1, 21G83
Processor: 8 cpus, 64bit, little endian, Apple M2
CC version: Apple clang version 13.0.0 (clang-1300.0.29.30)

getwd: /Users/danawoodman/v
vmodules: /Users/danawoodman/.vmodules
vroot: /Users/danawoodman/v
vexe: /Users/danawoodman/v/v
vexe mtime: 2022-08-30 01:28:32
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 e355ae7

Git version: git version 2.32.0 (Apple Git-132)
Git vroot status: weekly.2022.34-48-ge355ae7b
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 46662e20
```

### VLS info 

n/a

## Problem Description
Running `v ls --install` as stated in the docs fails using the latest version of V with:

```shell
$: v ls --install
cannot compile `/Users/danawoodman/v/cmd/tools/vls.v`: 
builder error: Your V installation may be out-of-date. Try removing `thirdparty/tcc/` and running `make`

$: v -v
V 0.3.0 a689641
```

I've followed the instructions but it still fails.

I've installed V by cloning the git repo and running `make` as instructed in V's readme

## Expected Output
It to install VLS

## Actual Output
See above

## Steps to Reproduce
See above

**Comment by danawoodman** [comment]
Thanks!

**Comment by SilverTab** [comment]
Getting the same error on an M1 Pro mac.

**Comment by JalonSolov** [comment]
You have a rather old version of V.  Try `v up` to get the latest, then try again.

Current version is `V 0.3.1 085a09e`.

**Comment by SilverTab** [comment]
I tried on the latest one, same result:

```
% v --version
V 0.3.1 afe7166

% v ls --install           
cannot compile `/Users/jeannicolas/Downloads/v/cmd/tools/vls.v`: 
builder error: Your V installation may be out-of-date. Try removing `thirdparty/tcc/` and running `make`
```

**Comment by SilverTab** [comment]
Looks like this was due to my system having 2 versions of OpenSSL installed (one via homebrew, and a system one) and V was compiled using the wrong one. Following the instructions at the end of this issue, I was able to fix it: https://github.com/vlang/v/issues/14888

However, now I'm back to where I was on my intel mac, which is that the language server is installed, and runs fine from Terminal, but it just doesn't work at all from VS Code... if I set the mode to stdio, it starts, but it's never able to complete anything 
<img width="323" alt="image" src="https://user-images.githubusercontent.com/15052/190903333-6fd2fc40-16a5-456f-893d-8fa09724def6.png">

If I set it to tcp, it fails to boot, with the following error:
`[Error - 9:01:24 AM] Connection to server is erroring. Shutting down server.`

**Comment by JalonSolov** [comment]
Try https://blog.vosca.dev/meet-v-analyzer/ instead, now that it is released.
