### ISSUE TITLE
VLS doesn't handle zombie process (v)

### ISSUE THREAD

**Issue by iacore** [vlang/vls#394]
vls version 0.0.1.8af4c9e

## Problem Description
VLS spawn `v` processes but doesn't `wait()` on them. The result is, in `top` a lot of zombie processes are under vls.

It doesn't affect usage. It just clutters process view.

## Steps to Reproduce

1. Use VLS in a project
2. Run `htop` and enable tree view with `t`

**Comment by SirZenith** [comment]
Start one VLS instance by `v ls`, then run `v ls` again in another terminal session. One should see the second command gets stuck at startup phase.

New text editor window would failed to spawn VLS if another VLS instance is running. And after this editor quite, VLS would be left in process tree, because it couldn't response to shutdown request at this point.

**Comment by JalonSolov** [comment]
Try https://blog.vosca.dev/meet-v-analyzer/ instead, now that it is released.
